### ISSUE TITLE
Uncaught Error: PCRE does not support \L, \l, \N{name}, \U, or \u

### ISSUE THREAD

**Issue by weihaosky** [richrace/highlight-selected#169] opened 2018-04-11 12:26 UTC
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Ubuntu 16.04.4
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.13.1

### Stack Trace

Uncaught Error: PCRE does not support \L, \l, \N{name}, \U, or \u

```
At /usr/share/atom/resources/app.asar/node_modules/superstring/index.js:246

Error: PCRE does not support \L, \l, \N{name}, \U, or \u
    at TextBuffer.findAllInRangeSync (/app.asar/node_modules/superstring/index.js:246:44)
    at TextBuffer.module.exports.TextBuffer.findAllInRangeSync (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1167:32)
    at TextBuffer.module.exports.TextBuffer.scanInRange (/usr/share/atom/resources/app/node_modules/text-buffer/lib/text-buffer.js:1080:32)
    at TextEditor.scanInBufferRange (/usr/share/atom/resources/app/src/text-editor.js:3378:73)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:151:12)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:136:10
    at Array.forEach (native)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:135:27)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:62:8
```

### Commands

```
     -3:23.5.0 core:copy (input.hidden-input)
     -0:57.2.0 core:undo (input.hidden-input)
  2x -0:55.5.0 core:redo (input.hidden-input)
     -0:46.4.0 editor:toggle-line-comments (input.hidden-input)
     -0:33.9.0 core:copy (input.hidden-input)
```

### Non-Core Packages

```
atom-ctags 5.1.2 
goto-definition 1.3.4 
highlight-selected 0.13.1 
hyperclick 0.1.3 
js-hyperclick 1.11.0 
language-latex 1.1.1 
latex 0.50.0 
pdf-view 0.68.0 
```

**Comment by richrace** [comment] 2018-04-11 12:35
Duplicate of https://github.com/richrace/highlight-selected/issues/167

**Closed by richrace** 2018-04-11 12:35 UTC
