### ISSUE TITLE
Deprecation warnings in Atom 1.13.0

### ISSUE THREAD

**Issue by mneumark** [richrace/highlight-selected#138] opened 2017-01-11 00:04 UTC
Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo-selectors, and prepend all your syntax selectors with syntax--. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:
```
:host atom-text-editor .highlight.highlight-selected .region, atom-text-editor atom-text-editor .highlight.highlight-selected .region, atom-text-editor::shadow atom-text-editor .highlight.highlight-selected .region => :host atom-text-editor .highlight.highlight-selected .region, atom-text-editor atom-text-editor .highlight.highlight-selected .region, atom-text-editor.editor atom-text-editor .highlight.highlight-selected .region
:host .highlights .highlight-selected .region, atom-text-editor .highlights .highlight-selected .region, atom-text-editor::shadow .highlights .highlight-selected .region => :host .highlights .highlight-selected .region, atom-text-editor .highlights .highlight-selected .region, atom-text-editor.editor .highlights .highlight-selected .region
:host .highlights .highlight-selected .region, atom-text-editor .highlights .highlight-selected .region, atom-text-editor::shadow .highlights .highlight-selected .region => :host .highlights .highlight-selected .region, atom-text-editor .highlights .highlight-selected .region, atom-text-editor.editor .highlights .highlight-selected .region
:host .highlights .highlight-selected.background .region, atom-text-editor .highlights .highlight-selected.background .region, atom-text-editor::shadow .highlights .highlight-selected.background .region => :host .highlights .highlight-selected.background .region, atom-text-editor .highlights .highlight-selected.background .region, atom-text-editor.editor .highlights .highlight-selected.syntax--background .region
:host .highlights .highlight-selected.light-theme .region, atom-text-editor .highlights .highlight-selected.light-theme .region, atom-text-editor::shadow .highlights .highlight-selected.light-theme .region => :host .highlights .highlight-selected.light-theme .region, atom-text-editor .highlights .highlight-selected.light-theme .region, atom-text-editor.editor .highlights .highlight-selected.light-theme .region
:host .highlights .highlight-selected.light-theme.background .region, atom-text-editor .highlights .highlight-selected.light-theme.background .region, atom-text-editor::shadow .highlights .highlight-selected.light-theme.background .region => :host .highlights .highlight-selected.light-theme.background .region, atom-text-editor .highlights .highlight-selected.light-theme.background .region, atom-text-editor.editor .highlights .highlight-selected.light-theme.syntax--background .region
```
Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by greatislander** [comment] 2017-01-11 16:44
Dupe of https://github.com/richrace/highlight-selected/issues/131

**Closed** 2017-01-11 17:43 UTC

**Comment by zyf0330** [comment] 2017-01-13 03:59
It seems that update for Atom 1.13.0 makes old version like 1.12.* cannot work normally.

**Comment by richrace** [comment] 2017-01-13 09:41
Well following advice from (here)[http://flight-manual.atom.io/shadow-dom/sections/removing-shadow-dom-styles/#when-should-i-migrate-my-themepackage]:

- "If you already want to test the migration on master or Beta channel, make sure to change your package.json file to `"engines": { "atom": ">=1.13.0 <2.0.0" }`. This will prevent Atom from updating your theme or package before the user also updates Atom to version 1.13."

Difference between the latest version and the old version:
https://github.com/richrace/highlight-selected/blob/v0.11.2/package.json#L12
https://github.com/richrace/highlight-selected/blob/v0.12.0/package.json#L12

I would say that it's Atom.

**Comment by zyf0330** [comment] 2017-01-13 09:46
I know, that is strange. Atom alerts me that packages are deprecated. And after that I know Atom has a newer version, it doesn't tell me.
