### ISSUE TITLE
Need to highlight variable names starting with $ in Perl as well

### ISSUE THREAD

**Issue by ericcirone** [richrace/highlight-selected#107] opened 2015-11-30 19:00 UTC
I see you added special case to catch names with "$" in PHP. This is needed for Perl too. If you hightlight "$var1" you will not get any matches. If you turn off whole word only, then it works.

**Comment by PhiLhoSoft** [comment] 2016-09-01 09:10
Actually, the root of the problem is probably from the borrowed code from find-and-replace module:

https://github.com/atom/find-and-replace/issues/576

So the behavior with regard to non word chars should be fixed, instead of adding exceptions for a limited number of languages... (should be applied to JavaScript, Java, Stylus and other related CSS languages, perhaps Ruby?, and so on).
And the problem goes beyond: if I want to add . and # to the word chars of CSS, when I double-click `#FFF` or `.foo` they are wholly selected, but other occurrences are not highlighted.
While foo-bar is, perhaps because of another special case in code...

**Comment by mj41** [comment] 2017-02-07 07:23
Probably related to: #73, #141, #132, #117, #88

**Comment by mj41** [comment] 2017-02-07 07:30
FYI: You can disable "Only Highlight Whole Words" to workaround for language-perl "Non Word Characters" (`/\()"':,.;<>~!@#$%^&*|+=[]{}``?-…` ). Of course both `$foo` and `$foobar` will be highlighted if you select `$foo`.

**Comment by richrace** [comment] 2018-06-23 15:18
See #174

**Closed by richrace** 2018-06-23 15:18 UTC
