### ISSUE TITLE
HighlightedAreaView.onDidAddMarker is deprecated.

### ISSUE THREAD

**Issue by TheSeg** [richrace/highlight-selected#147] opened 2017-03-23 21:58 UTC
Deprecation warning on version 0.13.0 (Atom 1.15.0). This issue is from the auto generated button from the deprecation cop.

Please do not use. This method will be removed.
```
HighlightedAreaView.onDidAddMarker (/Users/jseggerson/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:62:12)
onDidAddMarker (/Users/jseggerson/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:3:59)
MinimapHighlightSelected.init (/Users/jseggerson/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:58:30)
init (/Users/jseggerson/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:3:59)
MinimapHighlightSelected.consumeHighlightSelectedServiceV1 (/Users/jseggerson/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:28:21)
Provider.provide (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52)
```

**Comment by richrace** [comment] 2017-03-23 21:59
This pull requested needs to be merged: https://github.com/atom-minimap/minimap-highlight-selected/pull/39

**Comment by rafro** [comment] 2017-03-24 04:22
How would one go about merging this pull request?

**Comment by arsari** [comment] 2017-03-24 14:04
I get 2 deprecation warning on version 0.13.1 on Atom 1.15.0...

```
Please do not use. This method will be removed.
REPORT ISSUE
HighlightedAreaView.onDidAddMarker - /Users/arsari/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:62:12
onDidAddMarker - /Users/arsari/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:3:59
MinimapHighlightSelected.init - /Users/arsari/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:58:30
init - /Users/arsari/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:3:59
MinimapHighlightSelected.consumeHighlightSelectedServiceV1 - /Users/arsari/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:28:21
Provider.provide - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52

Please do not use. This method will be removed.
REPORT ISSUE
HighlightedAreaView.onDidAddSelectedMarker - /Users/arsari/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:69:12
onDidAddSelectedMarker - /Users/arsari/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:3:59
MinimapHighlightSelected.init - /Users/arsari/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:63:30
init - /Users/arsari/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:3:59
MinimapHighlightSelected.consumeHighlightSelectedServiceV1 - /Users/arsari/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:28:21
Provider.provide - /Applications/Atom.app/Contents/Resources/app.asar/node_modules/service-hub/lib/provider.js:29:52
```

**Comment by JeffCleverley** [comment] 2017-03-24 17:30
Same two deprecations as above

**Comment by Cherkah** [comment] 2017-03-25 02:20
Same two deprecations as above

**Comment by greenais** [comment] 2017-03-26 08:05
Same here

**Comment by carrodher** [comment] 2017-03-26 17:18
Same here for 1.16.0-beta0

**Comment by franciscoestevao** [comment] 2017-03-26 18:16
same

**Comment by Astlvk** [comment] 2017-03-27 00:48
Same here for 1.16.0-beta0

**Comment by Gscdae** [comment] 2017-03-27 01:18
Same here for 0.13.1

**Comment by juvevood** [comment] 2017-03-27 01:42
Same here for 0.13.1

**Comment by rkabrahpudi** [comment] 2017-03-27 06:53
Same here 0.13.1

**Comment by akaybagorov** [comment] 2017-03-27 07:40
+1

**Comment by bisinakeshara** [comment] 2017-03-27 23:04
just updated and same here for 0.13.1 in atom 1.15.0

**Comment by dqfan2012** [comment] 2017-03-27 23:27
Same.

**Comment by bbroens** [comment] 2017-03-28 00:33
Likewise

**Comment by okonomiyaki3000** [comment] 2017-03-28 06:10
Guys stop.. He got the message. You're not contributing anything.

**Comment by richrace** [comment] 2017-03-28 07:05
I've locked this issue as this is caused by another package using an API that causes bugs.

Once this pull request gets merged, the deprecated warnings will go away: https://github.com/atom-minimap/minimap-highlight-selected/pull/39

**Closed** 2017-03-31 13:07 UTC
