### ISSUE TITLE
Uncaught Error: PCRE does not support /L, \l, \N{name}, \U, or \u

### ISSUE THREAD

**Issue by sumsar10171** [richrace/highlight-selected#168] opened 2018-04-06 13:51 UTC
**Atom**: 1.25.1 x64
**Electron**: 1.7.11
**OS**: Microsoft Windows 10 Enterprise
**Thrown From**: [highlight-selected](https://github.com/richrace/highlight-selected) package 0.13.1

### Stack Trace

Uncaught Error: PCRE does not support \L, \l, \N{name}, \U, or \u

```
At C:\Users\Sumsar\AppData\Local\atom\app-1.25.0\resources\app.asar\node_modules\superstring\index.js:246

Error: PCRE does not support \L, \l, \N{name}, \U, or \u
    at TextBuffer.findAllInRangeSync (/app.asar/node_modules/superstring/index.js:246:44)
    at TextBuffer.module.exports.TextBuffer.findAllInRangeSync (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1167:32)
    at TextBuffer.module.exports.TextBuffer.scanInRange (~/AppData/Local/atom/app-1.25.1/resources/app/node_modules/text-buffer/lib/text-buffer.js:1080:32)
    at TextEditor.scanInBufferRange (~/AppData/Local/atom/app-1.25.1/resources/app/src/text-editor.js:3378:73)
    at HighlightedAreaView.module.exports.HighlightedAreaView.highlightSelectionInEditor (/packages/highlight-selected/lib/highlighted-area-view.coffee:151:12)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:136:10
    at Array.forEach (native)
    at HighlightedAreaView.module.exports.HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:135:27)
    at HighlightedAreaView.handleSelection (/packages/highlight-selected/lib/highlighted-area-view.coffee:1:1)
    at /packages/highlight-selected/lib/highlighted-area-view.coffee:62:8
```

### Commands

```
  8x -4:35.7.0 core:move-down (input.hidden-input)
     -4:33.8.0 core:move-up (input.hidden-input)
  6x -4:33 editor:select-to-beginning-of-word (input.hidden-input)
     -4:31.6.0 intentions:highlight (input.hidden-input)
     -4:31.3.0 core:cut (input.hidden-input)
  5x -4:31.1.0 core:move-up (input.hidden-input)
     -4:29.9.0 snippets:next-tab-stop (input.hidden-input)
     -4:29.9.0 snippets:expand (input.hidden-input)
     -4:29.9.0 editor:indent (input.hidden-input)
     -4:29.6.0 intentions:highlight (input.hidden-input)
     -4:29.5.0 core:paste (input.hidden-input)
  6x -4:29.3.0 core:move-down (input.hidden-input)
  4x -4:28.2.0 core:select-up (input.hidden-input)
  2x -4:27.4.0 core:backspace (input.hidden-input)
     -4:26.5.0 intentions:highlight (input.hidden-input)
     -4:26.4.0 core:save (input.hidden-input)
```

### Non-Core Packages

```
autoclose-html 0.23.0 
autocomplete-html-entities 0.2.0 
busy-signal 1.4.3 
file-icons 2.1.18 
highlight-selected 0.13.1 
intentions 1.1.5 
language-blade 0.39.0 
language-vue 0.23.1 
laravel 0.7.1 
linter 2.2.0 
linter-htmlhint 1.4.0 
linter-jshint 3.1.6 
linter-php 1.5.1 
linter-ui-default 1.7.1 
pigments 0.40.2 
platformio-ide-terminal 2.8.1 
rest-client 1.3.1 
```

**Comment by richrace** [comment] 2018-04-06 13:52
Duplicate of https://github.com/richrace/highlight-selected/issues/167

**Closed by richrace** 2018-04-06 13:52 UTC
