### ISSUE TITLE
HighlightedAreaView.onDidAddSelectedMarker is deprecated.

### ISSUE THREAD

**Issue by el-psycho** [richrace/highlight-selected#149] opened 2017-03-23 22:28 UTC
Deprication warning on highlight-selected 0.13.0, Atom 1.15.0

Please do not use. This method will be removed.
```
HighlightedAreaView.onDidAddSelectedMarker (/home/kevin/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:67:12)
onDidAddSelectedMarker (/home/kevin/.atom/packages/highlight-selected/lib/highlighted-area-view.coffee:3:59)
MinimapHighlightSelected.init (/home/kevin/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:63:30)
init (/home/kevin/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:3:59)
MinimapHighlightSelected.consumeHighlightSelectedServiceV1 (/home/kevin/.atom/packages/minimap-highlight-selected/lib/minimap-highlight-selected.coffee:28:21)
Provider.provide (/usr/lib/atom/node_modules/service-hub/lib/provider.js:34:52)
```

**Comment by arsari** [comment] 2017-03-24 04:50
same with me...

**Comment by richrace** [comment] 2017-03-24 07:59
This pull requested needs to be merged: https://github.com/atom-minimap/minimap-highlight-selected/pull/39

**Comment by carrodher** [comment] 2017-03-26 17:19
Same here for 1.16.0-beta0

**Comment by juvevood** [comment] 2017-03-27 01:43
Same here for 0.13.1

**Comment by vitorlee** [comment] 2017-03-27 01:55
Ver 0.13.1, still not fixed

**Comment by akaybagorov** [comment] 2017-03-27 07:40
+1

**Comment by richrace** [comment] 2017-03-28 07:05
I've locked this issue as this is caused by another package using an API that causes bugs.

Once this pull request gets merged, the deprecated warnings will go away: https://github.com/atom-minimap/minimap-highlight-selected/pull/39

**Closed** 2017-03-31 13:06 UTC
